version: 0.0
os: linux
files:
  - source: /dist
    destination: /home/ubuntu/web/client/greendongwha_client_dist/dist
    overwrite: yes
file_exists_behavior: OVERWRITE
   
hooks:
  BeforeInstall:
    - location: Scripts/deployArchive.sh
      timeout: 300
      runas: root
    - location: Scripts/deployHookbeforeInstall.sh
      timeout: 300
      runas: root